### ISSUE TITLE
Parse error when loading a component with a resource

### ISSUE THREAD

**Issue by cpetig** [peterhuene/wasmbuilder.app#8]
When I tried to load a simple component with resources into wasmbuilder I got this error message:

failed to parse component: export name `[constructor]my-object` is not valid
resource used in function does not have a name in this context (at offset [0xc)

[mod2.zip](https://github.com/peterhuene/wasmbuilder.app/files/11995476/mod2.zip)

**Comment by peterhuene** [comment]
Hi @cpetig. Thanks for the report!

The support for resources is undergoing a lot of changes at the moment, so I suspect that wasmbuilder needs to bump its dependencies at the very least.

**Comment by peterhuene** [comment]
I was able to update the dependencies to latest now that `wasm-tools` published new crates this morning.

I'm deploying the changes to the site now.

**Comment by peterhuene** [comment]
The changes have been deployed and you should now be able to add the component to the graph (note, however, the component here is a WIT package component with no implementation, so not terribly useful in a composition).

**Comment by cpetig** [comment]
Import now works nicely, thank you! (At least it loads and displays the wit but without displaying the interfaces)
